### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by poppy0293** [yyliu01/RPL#1]
I have downloaded the preprocessed data, but the structure is a little different with the code data structure. And I download the original dataset but the structure is still different. Could you upload the link of your suitable dataset? Or is there any easy way to solve the problem? Thank you very much!

**Comment by yyliu01** [comment]
Hi @Poppy-yyz 

Thanks a lot for your interest! Could you please double check the tree structure in [here](https://github.com/yyliu01/RPL/blob/main/docs/installation.md)? If it doesn't work for you, please give me more details about which dataset you need me to help.

Cheers,
Yuyuan

**Comment by yyliu01** [comment]
I've uploaded the related datasets (excluding COCO) in this [link](https://drive.google.com/drive/u/0/folders/1_5rZgWEDT9VbWch5dTkXWAOddUGqMmgE), please feel free to download. You can found the modified COCO dataset in [this repo](https://github.com/robin-chan/meta-ood).

Good luck.

**Comment by poppy0293** [comment]
Got it!  It helps!  Thank you!

**Comment by raj4432** [comment]
> I've uploaded the related datasets (excluding COCO) in this [link](https://drive.google.com/drive/u/0/folders/1_5rZgWEDT9VbWch5dTkXWAOddUGqMmgE), please feel free to download. You can found the modified COCO dataset in [this repo](https://github.com/robin-chan/meta-ood).
> 
> Good luck.

Hello,
The dataset you uploaded doesn't have the COCO dataset in it, making it hard to reproduce results. Would you mind adding the COCO dataset in it too since it's tedious to obtain them? Thanks.

**Comment by yyliu01** [comment]
@raj4432 Fair enough. I've uploaded it.

Cheers
