### ISSUE TITLE
What is the meaning of the result page for CityScapes mIOU? 

### ISSUE THREAD

**Issue by Orange-rightperson** [yyliu01/RPL#11]
Is it for the inline segmentation? And I run the test.py get a Cityscapes mIOU, can I campare the result with your result ?

**Comment by yyliu01** [comment]
Hi @Orange-rightperson 

Sure, of course! You can uncomment the code in [here](https://github.com/yyliu01/RPL/blob/130ba22a1fc581c63f798ea7c6aed3427ba4d5f7/rpl_corocl.code/test.py#L101) to inference. 

After the submission to the Cityscapes website, you will have an official report (like the one I reported in [here](https://www.cityscapes-dataset.com/anonymous-results/?id=e51cc63dc225379f5a974d54cec04d6a4135481446d0180c3a950bb7d96d8c4c)). You can also work on the validation set, while the results should match the Fishyscapes leader board (in [here](https://fishyscapes.com/results)).

Cheers,
Yuyuan
