### ISSUE TITLE
Would you please tell me how you mix the inline img like cityscapes with the ood image like coco?

### ISSUE THREAD

**Issue by Orange-rightperson** [yyliu01/RPL#12]
I see that you extact ood mask from coco ,and how you mix the mask with cityscapes image?

**Comment by yyliu01** [comment]
Hi @Orange-rightperson 

We describe such process in the paper 
![image](https://github.com/yyliu01/RPL/assets/102338056/c992c423-2f17-4e65-a8a5-83bb22ff973b)
, where we crop the partial image from COCO and mix (overlap) it to the inlier image (from Cityscape).

Such operation is performed in the dataloader, and in this [function](https://github.com/yyliu01/RPL/blob/130ba22a1fc581c63f798ea7c6aed3427ba4d5f7/rpl.code/dataset/cityscapes_coco.py#L45).

**Comment by Orange-rightperson** [comment]
Thank you @yyliu01 
Is the position where to overlap coco and mix it to de inlier image fixed? And what if the coco image shield the object in inlier image?

**Comment by yyliu01** [comment]
Hi @Orange-rightperson , it's in [here](https://github.com/yyliu01/RPL/blob/130ba22a1fc581c63f798ea7c6aed3427ba4d5f7/rpl.code/dataset/data_loader.py#L75)!

Cheers,
Yuyuan

**Comment by Orange-rightperson** [comment]
Thank you!
