### ISSUE TITLE
nan check 1

### ISSUE THREAD

**Issue by Porphy** [yyliu01/RPL#13]
![image](https://github.com/yyliu01/RPL/assets/92923476/053e738a-b2a6-4a4f-8ae2-e85d635dad50)
Hi, @yyliu01. Thank you for your work. I encountered a result of "nan" in an experiment(nan check 1). May I ask what could be the possible reasons for this?

**Comment by yyliu01** [comment]
Hi @Porphy 

Thanks so much for your interest!
 
May I ask whether you follow the instruction (in this [page](https://github.com/yyliu01/RPL/blob/main/docs/installation.md)) to install the same deployments as ours? 

Based on the provided report, I've noticed that the contrastive loss is 0, which means it doesn't detect OE anomaly objects in the batch. Could you please check the batch size and the input resolution?

Cheers,
Yuyuan

**Comment by yyliu01** [comment]
I'm closing the issue. Please feel free to reopen if you question is not solved.

**Comment by Porphy** [comment]
Thank you very much for your response. I adjusted the input resolution to a suitable value and reduced the learning rate, which resolved the issue. And I have not encountered such an issue in the subsequent experiments again!

**Comment by yyliu01** [comment]
Hi @Porphy 

Glad to hear that! Thanks for your interest again.

Cheers,
Yuyuan
