### ISSUE TITLE
CUDA OUT OF MEMORY

### ISSUE THREAD

**Issue by feritstar** [yyliu01/RPL#14]
Hi, I'm trying to run inference as you mentioned, but instead I've gotten this error every time;
RuntimeError: CUDA out of memory. Tried to allocate 602.00 MiB (GPU 0; 5.70 GiB total capacity; 2.97 GiB already allocated; 340.50 MiB free; 3.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Can you help me about it?
Thanks

**Comment by yyliu01** [comment]
Hi @feritstar 

Sorry for the late reply. Unfortunatelly I can't help with such hardware issue, could you try the code to the GPU with better capacity? Alternatively, you could run the code on the images with lower resolution.

Thanks for you interest.

Cheers,
Yuyuan
