### ISSUE TITLE
Ask about the city_scape used for training

### ISSUE THREAD

**Issue by WenjieZhao1** [yyliu01/RPL#3]
According to the installation docoument, the cityscapes could be downloaded from synboost GitHub. But the dataset from synboost GitHub don't includes val set of cityscapes. Besides, the pixel of downloaded label only includes 0 or 1 to represent if that class is OoD. If I want to recurrence the code, could I download original dataset from official website and use labelIds items of annotation? There is three kinds of image annotations , such as xxx_color.png, xxx_instanceIds.png, xxx_labelIds.png. Is that right to use xxx_labelIds.png as label?

**Comment by yyliu01** [comment]
Hi @zzwj66 

Sorry for the confuse and late response. Please find our datasets link in this [issue](https://github.com/yyliu01/RPL/issues/1).
I'll modify the documents.

Cheers,
Yuyuan

**Comment by WenjieZhao1** [comment]
Thans your for your reply.

Best regards,
Wenjie
