### ISSUE TITLE
推理速度问题

### ISSUE THREAD

**Issue by skming666** [yyliu01/RPL#6]
RPL 推理阶段 每张图片耗时200多ms，感觉还是比较慢的，理论上这个模型，官方能达到什么速度？FPS

**Comment by yyliu01** [comment]
hey @skming666 ,
谢谢对我们的项目感兴趣。目前RPL的架构只有一个ASPP, 应该不会对原有的DeepLabV3+带来太多的inference负担。请问您是在[这一行](https://github.com/yyliu01/RPL/blob/0dd496d9582cbb69c266e26c993b12a29e4b9b4d/rpl_corocl.code/model/wide_network.py#L180C9-L180C38)measure RPL的inference速度吗? 因为RPL在inference里只额外占用了这一行，其他时间是原本segmentation网络做闭集分割所必须占用的时间。

我们使用单张RTXA6000测速, 
在 SegmentMeIfYouCan/Fishyscape 中测速, RPL所占用的额外速度为 ~ 0.76 (ms/case)
<img width="742" alt="Screen Shot 2023-08-23 at 2 14 14 pm" src="https://github.com/yyliu01/RPL/assets/102338056/40fe1427-e1bc-4c76-a0fc-3e0d3d38a190">

测速用的是time.time():
```
# x 为之前的time checkpoint
(time.time() - x) * 1000
```
Cheers,
Yuyuan

**Comment by yyliu01** [comment]
不好意思, 上面的答案忘记了measure 上采样和过semantic head的时间了。
正确的测速应该是测量以下这三行:
```
res_, proj_ = self.residual_block(x_in_, upsample_size=m2.size()[2:])
dec2 = self.final(dec0 + res_)
out2 = Upsample(dec2, x_size[2:])
```

最后, 正确的RPL的架构的inference的时间是在0.9~1.2 (ms/case)之间。
