### ISSUE TITLE
没有异物的道路上仍然会有加亮显示部分，这个属于误报（异物）？

### ISSUE THREAD

**Issue by skming666** [yyliu01/RPL#7]
[我进行了个测试对比，道路上有异物时，可以对异物进行加亮显示；但是如果道路上没有异物时，只有车道线，这个时候仍然会有加亮显示的部分（车道线加亮会被认为是异物）；怎样才能实现在没有异物的道路上，图像不进行加亮显示？
![123](https://github.com/yyliu01/RPL/assets/75620929/b47c61cd-713b-4b04-bc7b-d1cdba060dc8)

**Comment by yyliu01** [comment]
Hey @skming666 

是的 这个是False Positive的误报, 但是目前没有很好的办法解决。因为上传的第二行图像和原本inlier模型训练的数据集 (i.e., cityscape) 在不同的domain, 所以inlier的预测可能会出现这种情况。目前的RPL只能做到对出现的异常物体非常敏感, 但是对**HARD** inlier无能为力。

比如在公式 eq. 5 中, RPL对inlier的预测是基于原网络能够有很低的uncertainty的假设上的。
<img width="324" alt="Screen Shot 2023-08-24 at 3 46 29 pm" src="https://github.com/yyliu01/RPL/assets/102338056/a72c9404-ca4b-4889-a593-0bc8e5a4bbf7">

我们在图3, 中也特意标出了这种 hard inlier 可能会被预测错的情况 (图 (c)的红圈里有inlier).
<img width="324" alt="Screen Shot 2023-08-24 at 3 47 03 pm" src="https://github.com/yyliu01/RPL/assets/102338056/b9cb016e-410c-4433-93c7-054657c462f8">

潜在的解决办法是, fine-tuning close-set segmentation的模型, 让他对不同的环境的inlier更鲁棒 (i.e., 产生较低的uncertianty). 这样RPL就可以在不改变inlier的情况下, 只点亮异常物体了.

Cheers,
Yuyuan
