### ISSUE TITLE
关于pretrained_ckpts

### ISSUE THREAD

**Issue by skming666** [yyliu01/RPL#8]
您好，我看那个md文件中写道；
### checkpoints

we follow [Meta-OoD](https://github.com/robin-chan/meta-ood) and use the deeplabv3+ checkpoint
in [here](https://github.com/NVIDIA/semantic-segmentation/tree/sdcnet). you'll need to put it in "ckpts/pretrained_ckpts" directory, and
**please note that downloading the checkpoint before running the code is necessary for our approach.**
这个checkpoint 是必须的，如果我训练自己的数据集分类只有7类；在训练时提示shape torch.Size([20, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 256, 1, 1])，两个size不匹配，这个理论上应该怎么解决？谢谢！

**Comment by yyliu01** [comment]
Hi @skming666 

请先预训练您的inlier模型, 然后保留checkpoint。
之后再用这个repository的代码来fine-tuning OE的OoD图像。

如果您还有相关custom dataset的问题, 您可以直接发我邮箱 yuyuan.liu@adelaide.edu.au.

cheers,
yuyuan

**Comment by skming666** [comment]
你好这个预训练inlier模型,是用哪个模型进行训练的，您有推荐吗？是https://github.com/NVIDIA/semantic-segmentation/tree/sdcnet吗

**Comment by yyliu01** [comment]
Hi @skming666 

是的 我们用的是这个ckpt。

Cheers,
Yuyuan
